services:

  pokefilter-backend:
    build:
      context: ./pokefilter/
    container_name: poke-filter
    ports:
      - "8081:8081"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  poke-react-app:
    build:
      context: ./poke-project-app/
    container_name: poke-react-app
    ports:
      - "3000:80"
    links:
      - pokefilter-backend